def Lab1():
    
    PNOUN1=input("Enter a plural noun: ")
    FNAME=input("Enter your name: ")
    NOUN1=input("Enter the newspaper name: ")
    LNAME=input("Enter your Last name: ")
    PNOUN2=input("Enter plural noun 2: ")
    PLACE1=input("Enter a place: ")
    PNOUN3=input("Enter a plural noun 3: ")
    PLACE2=input("Enter place 2: ")
    PNOUN4=input("Enter a plural noun 4: ")
    NOUN2=input("Enter noun 2: ")
    ADJECTIVE1=input("Enter Adjective: ")
    ADJECTIVE2=input("Enter Adjective 2: ")
    VERB=input("Enter a verb: ")
    ADJECTIVE3=input("Enter Adjective 3: ")

    print("")
    print("The Big Game !!!")
    print("")
    print("Hello there, sports",PNOUN1,"!")
    print("This is",FNAME,", talking to you from the press",NOUN1)
    print("in",LNAME,"Stadium, where 57,000 cheering",PNOUN2)
    print("have gathered to watch (the)",PLACE1,PNOUN3)
    print("take on (the)",PLACE2,PNOUN4,".")
    print("Even though the",NOUN2,"is shining, it's a/an",ADJECTIVE1)
    print("cold day with the temperature in the",ADJECTIVE2,"20s.")
    print("We'll be back for the opening",VERB,"-off after a few words")
    print("from our",ADJECTIVE3,"sponsor.")
    
Lab1()
